/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_skullmind_mbp_ffmpeg_info_OSInfo */

#ifndef _Included_cn_skullmind_mbp_ffmpeg_info_OSInfo
#define _Included_cn_skullmind_mbp_ffmpeg_info_OSInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_skullmind_mbp_ffmpeg_info_OSInfo
 * Method:    getOSString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_skullmind_mbp_ffmpeg_1info_OSInfo_getOSString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
