/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_skullmind_mbp_media_AudioCoder */

#ifndef _Included_cn_skullmind_mbp_media_AudioCoder
#define _Included_cn_skullmind_mbp_media_AudioCoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_skullmind_mbp_media_AudioCoder
 * Method:    readSamples
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_skullmind_mbp_media_AudioCoder_readSamples
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
