/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_skullmind_mbp_ffmpeg_info_OSInfo_Companion */

#ifndef _Included_cn_skullmind_mbp_ffmpeg_info_OSInfo_Companion
#define _Included_cn_skullmind_mbp_ffmpeg_info_OSInfo_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
