/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_skullmind_mbp_transcode_FFMpeg */

#ifndef _Included_cn_skullmind_mbp_transcode_FFMpeg
#define _Included_cn_skullmind_mbp_transcode_FFMpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_skullmind_mbp_transcode_FFMpeg
 * Method:    nativeCmd
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_skullmind_mbp_transcode_FFMpeg_nativeCmd
  (JNIEnv *, __attribute__((unused)) __attribute__((unused)) jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
