/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_skullmind_mbp_media_VideoCapture */

#ifndef _Included_cn_skullmind_mbp_media_VideoCapture
#define _Included_cn_skullmind_mbp_media_VideoCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_skullmind_mbp_media_VideoCapture
 * Method:    captureCameraData
 * Signature: ()Ljava/io/File;
 */
JNIEXPORT jint JNICALL Java_cn_skullmind_mbp_media_VideoCapture_captureCameraData
  (JNIEnv *, jobject,jobject);

#ifdef __cplusplus
}
#endif
#endif
