/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_skullmind_mbp_media_MediaPlayer */

#ifndef _Included_cn_skullmind_mbp_media_MediaPlayer
#define _Included_cn_skullmind_mbp_media_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_skullmind_mbp_media_MediaPlayer
 * Method:    supportMediaFormats
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_cn_skullmind_mbp_media_MediaPlayer_supportMediaFormats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
