/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_skullmind_mbp_transcode_FFMpeg */

#ifndef _Included_cn_skullmind_mbp_transcode_FFMpeg
#define _Included_cn_skullmind_mbp_transcode_FFMpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_skullmind_mbp_transcode_FFMpeg
 * Method:    nativeCmd
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_skullmind_mbp_transcode_FFMpeg_nativeCmd
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     cn_skullmind_mbp_transcode_FFMpeg
 * Method:    nativeCleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_skullmind_mbp_transcode_FFMpeg_nativeCleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
